version: '3.7'
services:

  sidzina-api:
    image: goreit/sidzina:4
    volumes:
      - sidzina-api-data:/root
    ports:
      - 8080:8080
#    depends_on:
#      - 'mongodb'
    networks:
      - goreit

#  mongodb:
#    image: mongo:4.0.0
#    volumes:
#      - mongodb-data:/data/db
#    ports:
#      - 27017:27017
#    command: mongod mongod --logpath /var/logs
#
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    networks:
#      - goreit

#  keycloak:
#    image: jboss/keycloak
#    ports:
#      - 8080:8080
#    environment:
#      DB_VENDOR: POSTGRES
#      DB_ADDR: postgres
#      DB_DATABASE: keycloak
#      DB_USER: postgres
#      DB_PASSWORD: postgres
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
#    volumes:
#      - keycloak-data:/var/lib/keycloak/data
#    networks:
#      - goreit
#    depends_on:
#      - postgres
#

#
#
#  postgres:
#    image: postgres
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: keycloak
#      PGDATA: var/lib/postgresql/data/pgdata
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    networks:
#      - goreit


#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 2000M
#    environment:
#      RABBITMQ_USERNAME: admin
#      RABBITMQ_PASSWORD: admin
#    volumes:
#      - rabbitmq-data:/data/mq
#    networks:
#      - goreit

networks:
  goreit:

volumes:
  sidzina-api-data:
  mongodb-data:
  rabbitmq-data:
#  solr-data:
#  postgres-data:
#  keycloak-data:


