apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidzina-dep
  labels:
    app: sidzina-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidzina
  template:
    metadata:
      labels:
        app: sidzina
    spec:
      containers:
        - name: sidzina
          image: goreit/sidzina:latest
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: gshop-svc
  labels:
    app: gshop
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: gshop