spring:
  data:
    mongodb:
      uri: mongodb://gore717171:wrhxkjb9@docdb-2022-03-27-05-41-13.c456meeeym59.eu-central-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&retryWrites=false
      database: goreit




