mongodb:
  max:
    pool:
      size: 300

spring:
  data:
    mongodb:
      uri: mongodb://azure-cosmodb-for-mongo:SCFonQMOiTYVL4sA4rEv16vMiqj738VTHaVsTHtSmy0tK3X8PCM6GdqQjMI1xsZoyBGass2CZ5OxmsHouCaKZQ==@azure-cosmodb-for-mongo.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@azure-cosmodb-for-mongo@
      database: goreit
  #      authentication-database: admin
  #      host: 192.168.0.187
  #      port: 27017
  #      password: root
  #      username: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
    application:
      name: Goreit

keycloak:
  realm: goreit
  resource: sidzina
  auth-server-url: http://192.168.0.187:8080/auth
  public-client: true
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  cors: true
  bearer-only: true
  securityConstraints[0]:
    authRoles[0]: user
    securityCollections[0]:
      name: user resource
      patterns: /products


logging:
  level:
    org:
      keycloak: TRACE
      springframework: INFO
#  cloud:
#    kubernetes:
#      discovery:
#        all-namespaces: true


server:
  port: 80

#ribbon:
#  http:
#    client:
#      enabled: true
pricing:
  commission: 0.00
  default:
    balance: 100
    coins: 200
  coins:
    multipler: 5
    divider: 10
