logging.file.path: logs

spring:
  data:
    mongodb:
      database:  goreit
      authentication-database: admin
      host: localhost:27017
      password: root
      username: root

keycloak:
  realm: goreit
  resource: sidzina
  auth-server-url: http://localhost:8080/auth
  public-client: true
  principal-attribute: preferred_username
  securityConstraints[0]:
    authRoles[0]: user
    securityCollections[0]:
      name: user resource
      patterns: /orders
