spring:
  data:
    mongodb:
      uri: mongodb://gore717171:wrhxkjb9@docdb-2022-03-27-07-01-35.cluster-c456meeeym59.eu-central-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: goreit

net:
  tls:
    mode: requireTLS
    certificateKeyFile: resources/rds-combined-ca-bundle.pem




